name: Automated Tests
run-name: Running automated tests.

on:
  push:
    branches:
      - "**"

jobs:
  testing-container:
    if: "contains(github.event.head_commit.message, '[testing]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Spin up testing container
        run: docker-compose -f docker-compose.test.yml up -d
      # - name: Sleep for 15 seconds
      #   run: sleep 15s
      #   shell: bash
      - name: Check logs
        run: docker logs gha-testing
      - name: Run automated tests
        run: docker exec gha-testing php vendor/phpunit/phpunit/phpunit tests/unit/Service/SomeApiTest.php
        shell: bash